import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="relative w-full h-72 flex items-center justify-center overflow-hidden">
          <Image
            src='/background.jpg'
            alt="A table full of spices"
            fill
            className="object-cover inset-0 -z-15 blur-xs"
          />

          <div className="absolute inset-0 -z-10 bg-amber-100/40"></div>

          <Image src='/logo-nobg.png' alt="Logo" width={200} height={200} />
        </header>

        {children}
      </body>
    </html>
  );
}
